package com.apexfission.android.carddetectionlite.ui.overlays

import com.apexfission.android.carddetectionlite.ui.overlays.animation.AnimatedDetectionBounds as AnimationAnimatedDetectionBounds
import com.apexfission.android.carddetectionlite.ui.overlays.animation.AnimationEffectsState as AnimationAnimationEffectsState
import com.apexfission.android.carddetectionlite.ui.overlays.animation.BoundingBoxCoordinates as AnimationBoundingBoxCoordinates
import com.apexfission.android.carddetectionlite.ui.overlays.animation.DetectionAnimationConfig as AnimationDetectionAnimationConfig
import com.apexfission.android.carddetectionlite.ui.overlays.animation.LockOnProgressState as AnimationLockOnProgressState
import com.apexfission.android.carddetectionlite.ui.overlays.animation.TrackingMetadata as AnimationTrackingMetadata

typealias AnimatedDetectionBounds = AnimationAnimatedDetectionBounds
typealias DetectionAnimationConfig = AnimationDetectionAnimationConfig
